health_reminders:
- To prevent eye strain, remember the 20-20-20 rule. Every 20 minutes, look at something 20 feet away for 20 seconds
- Drinking plenty of water and eating a healthy snack will help your focus.
- A positive mindset will help you play better. If you find yourself frustrated, take a small break to mentally reset.
- In online games, be kind to others. Take advantage of mute and report functionalities to block out toxic players.
- Check your posture. Use the g!ergonomics command for information on healthy posture while gaming.
- Breathe. Deep breaths will help maintain focus and reduce anxiety while gaming.

brightness:
  text: 
    |
      To prevent eye-strain, you should choose an appropriate screen brightness. Adjust your screen to match the lighting of the room.
      If you hold a piece of paper next to this white image, they should match in brightness.
  image: images/white.jpg 

posture:
  text: Keep good posture when gaming to avoid long term injuries or pain.
  image: images/posture.png

wrist:
  text: Streching is import to prevent wrist injury from long term gaming. Try this stretch.
  exercises:
    - text:
      |
        Prayer position stretch.
        1. Begin by pressing your palms and fingers together with your fingers pointing upward and your elbows pointing outward.
        2. Increase the intensity of the stretch by keeping your elbows in place and lowering your hands.
        3. You should feel a mild discomfort but no pain. Hold this stretch for 30 seconds.
      image: images/prayer.jpeg
    - text: 
      |
        Supine flexors stretch.
        1. Perform this stretch on both hands.
        2. Begin with your elbow straight and your palm facing upward.
        3. With your other hand, pull your wrist downward, stretching the palm side of your forearm.
        4. You should feel a mild discomfort but no pain. Hold this stretch for 30 seconds on each arm.
      image: images/supline.jpeg

mindfulness:
  text:
    |
      Mindfulness is the basic human ability to be fully present, aware of where we are and what we’re doing,
      and not overly reactive or overwhelmed by what’s going on around us.
      By practicing mindfulness, you can be more focused, aware, and calm while gaming. Try this exercise.
  exercises:
    -
      |
        1. Find a relaxed, comfortable position. You could be seated on a chair or on the floor on a cushion. Keep your back upright, but not too tight. Hands resting wherever they’re comfortable. Tongue on the roof of your mouth or wherever it’s comfortable.
        2. Notice and relax your body. Try to notice the shape of your body, its weight. Let yourself relax and become curious about your body seated here—the sensations it experiences, the touch, the connection with the floor or the chair. Relax any areas of tightness or tension. Just breathe.
        3. Tune into your breath. Feel the natural flow of breath—in, out. You don’t need to do anything to your breath. Not long, not short, just natural. Notice where you feel your breath in your body. It might be in your abdomen. It may be in your chest or throat or in your nostrils. See if you can feel the sensations of breath, one breath at a time. When one breath ends, the next breath begins.  
        4. Now as you do this, you might notice that your mind may start to wander. You may start thinking about other things. If this happens, it is not a problem. It's very natural. Just notice that your mind has wandered. You can say “thinking” or “wandering” in your head softly. And then gently redirect your attention right back to the breathing.
        5. Stay here for five to seven minutes. Notice your breath, in silence. From time to time, you’ll get lost in thought, then return to your breath.  
        6. After a few minutes, once again notice your body, your whole body, seated here. Let yourself relax even more deeply and then offer yourself some appreciation for doing this practice today.